document.getElementsByTagName("li")[2].innerHTML = "xiaozhang";
document.getElementsByTagName("li")[2].style.color = "pink";
document.getElementsByClassName("btn")[0].style.color = "red";
document.getElementById("title").innerHTML = "<em>Good Bye</em>";
document.querySelector("a").style.color = "green";
document.querySelector(".btn").innerHTML = "Do Not Click";
document.querySelector(".list a").innerHTML = "Gooooogle";
document.querySelector(".btn").style.backgroundColor = "yellow";
document.querySelector("h1").classList.add("huge");
//document.quertSelector("a").getAttribute("href");
document.querySelector("a").setAttribute("href", "https://www.bing.com");
